### ISSUE TITLE
Possible bug 

### ISSUE THREAD

**Issue by zhao-lun** [DarisaLLC/ridge_strands#1]
Hi,

I'm not entirely sure but shouldn't we pass line_out[4] as last argument (grady) 

```
lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[4]);
```
instead of [code](https://github.com/DarisaLLC/ridge_strands/blob/main/xcode/strands/strands/strands.cpp#L87)

```
lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[5]);
```

**Comment by githublqs** [comment]
I see the 

> Hi,
> 
> I'm not entirely sure but shouldn't we pass line_out[4] as last argument (grady)
> 
> ```
> lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[4]);
> ```
> 
> instead of [code](https://github.com/DarisaLLC/ridge_strands/blob/main/xcode/strands/strands/strands.cpp#L87)
> 
> ```
> lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[5]);
> ```
我也发现了这个问题,此外对于
方法 
void link::compute_contours(std::vector<int32_t> ismax, const std::vector<double>& eigval,
    const std::vector<double>& posx, const std::vector<double>& posy,
    const std::vector<double>& normx, const std::vector<double>& normy,
    const std::vector<double>& gradx, const std::vector<double>& grady)
我对参数的理解是:
 const std::vector<double>& posx, const std::vector<double>& posy,
    const std::vector<double>& normx, const std::vector<double>& normy,
    const std::vector<double>& gradx, const std::vector<double>& grady
这里面的x代表的是y，而y实际代表的x，
 row.push_back((float)posx[pos]);
col.push_back((float)posy[pos]);
既然是这样，那下面的nx，ny
  nx = -normy[pos];
 ny = normx[pos];

alpha = std::atan2(ny, nx);
是不是应该写成
nx = -normx[pos];
ny = normy[pos];
呢？
再者，cleartab 中的值是否也应该互换位置呢？

**Comment by gmnamra** [comment]
I am sorry for a long delay in responding. But you are correct. I will update. 

Thank you

**Comment by yaodix** [comment]
> I see the
> 
> > Hi,
> > I'm not entirely sure but shouldn't we pass line_out[4] as last argument (grady)
> > ```
> > lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[4]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead of [code](https://github.com/DarisaLLC/ridge_strands/blob/main/xcode/strands/strands/strands.cpp#L87)
> > ```
> > lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[5]);
> > ```
> 
> 我也发现了这个问题,此外对于 方法 void link::compute_contours(std::vector<int32_t> ismax, const std::vector& eigval, const std::vector& posx, const std::vector& posy, const std::vector& normx, const std::vector& normy, const std::vector& gradx, const std::vector& grady) 我对参数的理解是: const std::vector& posx, const std::vector& posy, const std::vector& normx, const std::vector& normy, const std::vector& gradx, const std::vector& grady 这里面的x代表的是y，而y实际代表的x， row.push_back((float)posx[pos]); col.push_back((float)posy[pos]); 既然是这样，那下面的nx，ny nx = -normy[pos]; ny = normx[pos];
> 
> alpha = std::atan2(ny, nx); 是不是应该写成 nx = -normx[pos]; ny = normy[pos]; 呢？ 再者，cleartab 中的值是否也应该互换位置呢？

我没有修改nx ny，这些修改线条属性（dark/light）和参数可以运行成功

**Comment by gmnamra** [comment]
You are correct. Thank you. ArmanOn Jan 12, 2024, at 07:22, yao Liu ***@***.***> wrote:﻿

I see the

Hi,
I'm not entirely sure but shouldn't we pass line_out[4] as last argument (grady)
lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[4]);

instead of code
lnk.compute_contours(ismax, line_out[0], line_out[5], line_out[6], line_out[1], line_out[2], line_out[3], line_out[5]);


我也发现了这个问题,此外对于 方法 void link::compute_contours(std::vector<int32_t> ismax, const std::vector& eigval, const std::vector& posx, const std::vector& posy, const std::vector& normx, const std::vector& normy, const std::vector& gradx, const std::vector& grady) 我对参数的理解是: const std::vector& posx, const std::vector& posy, const std::vector& normx, const std::vector& normy, const std::vector& gradx, const std::vector& grady 这里面的x代表的是y，而y实际代表的x， row.push_back((float)posx[pos]); col.push_back((float)posy[pos]); 既然是这样，那下面的nx，ny nx = -normy[pos]; ny = normx[pos];
alpha = std::atan2(ny, nx); 是不是应该写成 nx = -normx[pos]; ny = normy[pos]; 呢？ 再者，cleartab 中的值是否也应该互换位置呢？

我没有修改nx ny，这些修改线条属性（dark/light）和参数可以运行成功
